### PR TITLE
Deleted the unnecessary cpp file

### PR DESCRIPTION
**Pull request by ChristianPanov**

### CODE REVIEW

**Comment by ScaredStorm** [comment]
Hi,

Why did you create two separate pull requests?

**Comment by ChristianPanov** [comment]
Hi
Excuse me for this, I forgot to delete the file in the first pull request








 >-------- Оригинално писмо --------

 >От: Sander Boelhouwers ***@***.***

 >Относно: Re: [TheCherno/Hazel] Deleted the unnecessary cpp file (#429)

 >До: TheCherno/Hazel  

 >Изпратено на: 14.03.2021 13:25



 
 
  
  
  
Hi,  
  
Why did you create two separate pull requests?

**Comment by 3x3y3z3t** [comment]
Hi,

You can (and you should) add more commit to the first pull request instead of create another one.
You can delete the file and commit to the first PR's branch.

**Comment by LovelySanta** [comment]
Marking as duplicate of #428, leaving it open till they are merged.

**Pull request closed without merging**
