### PR TITLE
Fixing bug when trying to update submodules

### LINKED ISSUE #89: Updating submodules
It seems that submodules in Hazel/vendor are frozen on commits from many months ago, what is the process for updating these submodules to the latest commits of their respective repositories?

Cheers

### PR DESCRIPTION
**Pull request by ryanbbernstein**
Specifying branch for dear imgui and spdlog since both are using a non master branch

#### TODO
- [x] Update GLFW submodule (TheCherno/glfw#10)
- [x] Update ImGui submodule (TheCherno/imgui#7)

*EDIT by @LovelySanta:* resolves #89 (Closing keywords must be placed in initial post to work.)
*EDIT by @LovelySanta:* added todo list

### CODE REVIEW

**Comment by ryanbbernstein** [comment]
resolves #89

**Comment by LovelySanta** [comment]
Closing keywords must be placed in initial post.

**Comment by LovelySanta** [comment]
cherno just removed the warings in GLFW and pulled it in Hazel with https://github.com/TheCherno/Hazel/commit/24fb3bbacc3661edb7ae4a5c9d946f948b9dcecd.

So to at least merge this PR you have to pull the changes from ImGui (from cf5a93a to [5b0b18b](https://github.com/TheCherno/imgui/tree/5b0b18b099f6261a7895be9a04d218cf3e5d79b3)).

But that only contains changes for linux, which I wouldn't do then, but updating ImGui to pull in all the performance changes (and maybe potential memory leaks) should be pulled from source for sure. As mensioned before, I explained in https://github.com/TheCherno/Hazel/issues/89#issuecomment-524638028 how to make updates to the submodules.

**Comment by Puddlestomper** [comment]
I have made PRs to [TheCherno/glfw](https://github.com/TheCherno/glfw) and [TheCherno/imgui (docking)](https://github.com/TheCherno/imgui/tree/docking) to update them to newer versions.

Hazel still compiles and seems to run fine with them, but I have not done in-depth testing.

**Comment by LovelySanta** [comment]
@Puddlestomper Can you mension this PR in those two PR's you've made, this way there is a cross reference present. Then i'll also add them to the todo list of this PR.

**Comment by Puddlestomper** [comment]
Cherno has now merged both my PRs for the submodules and he then also updated the submodules himself. All that is left for this PR to do is to specify the branches.

**Comment by LovelySanta** [comment]
> All that is left for this PR to do is to specify the branches.

Updating to the new commits on those branches you mean.

**Comment by Puddlestomper** [comment]
> > All that is left for this PR to do is to specify the branches.
> 
> Updating to the new commits on those branches you mean.

Cherno has already updated the submodules (which is why this PR now has merge conflicts). So I'm not sure what you mean?

**Comment by ryanbbernstein** [comment]
I modified it to specify all branches a little while ago so I think it's good to go

**Comment by Puddlestomper** [comment]
I see. I was originally thinking we could just revert the actual changing of the submodules in this PR since Cherno has already updated the submodules in Hazel himself.

But I have now made a PR (ryanbbernstein/Hazel#3) to update this PR to the latest submodules which should also (I think) solve the merge conflicts.

**Comment by ryanbbernstein** [comment]
PR was merged

**Pull request merged**
