### PR TITLE
Start Project

### PR DESCRIPTION
**Pull request by AleksandarSherbula**
Added start project to be Sandbox in premake.

### CODE REVIEW

**Comment by AleksandarSherbula** [comment]
Not exactly sure what do you mean? prj.name is used as a reference to the project name when you are in its scope in premake. There is nothing that can be defined here(as far as i am aware of).

**Comment by vamidi** [comment]
Like startproject "%{prj.name}"

**Comment by AleksandarSherbula** [comment]
You can't do that, since it's out of scope of Sandbox project in premake. Otherwise, the script will have no idea what are you refering to.

**Comment by vamidi** [comment]
Ahh that's too bad alright thanks!

**Pull request merged**
