### PR TITLE
Removed Duplicate ImGui Window Creation

### PR DESCRIPTION
**Pull request by ultamatum**
#### Describe the issue (if no issue has been made)
Currently the ImGui Settings window creation is duplicated. This is unnecessary as to be included in the dockspace the window should be created after not within.

#### Proposed fix
Removed else statement and duplicate code.

### CODE REVIEW

**Comment by LovelySanta** [comment]
It must be created before the last `ImGui::End()` in order to be dockable, as demonstrated in the [video](https://www.youtube.com/watch?v=UljMVrQ_zYY). The implementation you've provided will not work as intended.

Cherno also mentioned that the editor will have a seperate project, so this is just temporary as the sandbox is the runtime testing while the dockspace will be part of the editor. This will become more clear in future videos.

**Comment by ultamatum** [comment]
It does work, it wasn't tested in the video. It just needs to be created after the line `ImGui::DockSpace(dockspace_id, ImVec2(0.0f, 0.0f), dockspace_flags);` to be included in the dockspace.

**Comment by LovelySanta** [comment]
oh ok, it didn't seem like that in the video. Let's first see how cherno implements the docking before trying to clean up the code base then.

**Comment by LovelySanta** [comment]
Now that Cherno moved Hazelnut to a seperate project (https://github.com/TheCherno/Hazel/commit/9ddc33488e50da9550023077227a4b973867c1c2), the duplicate creation in sandbox is also gone, and is not duplicated in Hazelnut itself. Closing this as resolved.

**Pull request closed without merging**
