### PR TITLE
Call the layer's OnDetach before deleting it.

### PR DESCRIPTION
**Pull request by IshoAntar**
the leaks where discovered in #125

### CODE REVIEW

**Comment by Puddlestomper** [comment]
I would just like to point out that this does not resolve the issue alone. Only with the other 3 PRs of yours is the issue resolved.

**Comment by IshoAntar** [comment]
How do i point that out?

**Comment by Puddlestomper** [comment]
I suggest you remove the closing keywords and we make a task list on the issue itself. I have suggested it there.

**Comment by IshoAntar** [comment]
OK, i'll edit my comments.

**Pull request closed without merging**
