### PR TITLE
Linux port

### PR DESCRIPTION
**Pull request by ppetraki**
Following from https://github.com/TheCherno/Hazel/issues/130

### CODE REVIEW

**Comment by LovelySanta** [comment]
instead of creating a seperate PR, could you contribute this to #82? However, I think this is all already implemented there.

**Comment by ppetraki** [comment]
It looks pretty much the same sans the issues I didn't know about/run into yet (resources). What's stopping #82 from being merged into mainline? As long as it doesn't disturb the windows build it should be fine. Clearly, duplication of effort is a problem.

**Comment by LovelySanta** [comment]
Currently it's just missing some filesystem solution, and cherno must mension it in his videos first. I'll close this (and #130) as duplicates of #82

**Comment by ppetraki** [comment]
OK. Sounds like a plan. I'll take a closer look at #82. Thanks.

**Pull request closed without merging**
