### PR TITLE
Creates the unique_ptr by using make_unique()

### PR DESCRIPTION
**Pull request by Simonmicro**
See: https://stackoverflow.com/questions/22571202/differences-between-stdmake-unique-and-stdunique-ptr-with-new
...if this project uses c++17

### CODE REVIEW

**Comment by WhoseTheNerd** [comment]
Sorry to say this to you, but there is another PR that does exactly like that on larger scale. Replacing all `new unique_ptr` with `std::make_unique`

**Comment by Simonmicro** [comment]
Hmm, i cant find an other request doing this (maybe it's inside the hidden dev branch?) - so I've created one. But when will the PR referenced by you merged? Otherwise I wouldn't created this PR...

**Comment by Puddlestomper** [comment]
I think he is referring to #129. I checked now and this change is not included there.

The reason is probably that this doesn't compile. You get:
`error C2259: 'Hazel::Window': cannot instantiate abstract class` and
`error C2664: 'Hazel::Window::Window(const Hazel::Window &)': cannot convert argument 1 from '_Ty' to 'const Hazel::Window &'`

So I think the solution is to leave this for a PR refactoring the various `Create` methods (as what #112 did) and then have the `Create` method for the `Window` return a `Scope` directly. Until then we need to use the `std::unique_ptr` constructor.

And since we do plan on using/use C++17 this change has no real effect anyway (as is said in your stackoverflow link).

**Comment by LovelySanta** [comment]
As @Puddlestomper said, this is the same as we did in #112. I'll mark this as duplicate. I won't close it just yet.

I think we should make an issue that contains all the things that have to happen in an upcomming code maintenance that we can reference towards in the future.

**Comment by LovelySanta** [comment]
See issue #140 that I mensioned in this https://github.com/TheCherno/Hazel/pull/139#issuecomment-535997732.

**Pull request closed without merging**
