### PR TITLE
Remove profile result json files from version control.

### PR DESCRIPTION
**Pull request by 0xworks**
Implements #182

### CODE REVIEW

**Comment by Puddlestomper** [comment]
Also, adding on to what FFMG said, where exactly is this temporary directory created? I definitely agree that these profiling files shouldn't be on the GitHub repo, but adding them to the gitignore or making a dedicated folder for them or both seems like a better idea than creating files outside of the solution folder to me.

**Comment by freeman40** [comment]
@Puddlestomper  The temporary directory isn't created - it is a guaranteed already-exists location.  It's %TEMP% on windows, or $TMPDIR on mac/linux (or failing that /tmp).

@FFMG  The profile result files weren't going to the exe directory.  They were going to the current working directory which may or may not be the exe directory.  For example, if you just run the project from within Visual Studio on Windows, then the profile result files end up in the Sandbox project directory (could be why they ended up getting committed)

I did consider just adding the filenames to .gitignore, but decided against that because the actual problem is that the files are created in the wrong place to begin with.  So adding to .gitignore seems like a workaround rather than a fix.
 
I chose the temp directory as the location to store these files as that seemed a natural place for files that we only want to look at for a little bit while doing profiling runs.

I'm totally fine with the exe folder being the location for these files though, (and this wouldn't require any change to .gitignore, since "bin" is already ignored).  If someone can tell me a cross-platform std-c++ way to get the current exe directory, then I can update the PR.

**Comment by Puddlestomper** [comment]
Looking at %TEMP% on my windows machine, it's really cluttered (~300 items) and I don't want to have to go looking through that every time I just want to check my profile result for Hazel. I would rather we keep it as is for now and add it to the .gitignore or make a dedicated folder for it as you suggested.

**Comment by LovelySanta** [comment]
What about just outputting it in a profiling folder or something?

**Comment by freeman40** [comment]
Yes, it would be more convenient to have the result files in the exe directory.  I'll update the PR.

**Comment by TheCherno** [comment]
Profile results should definitely not be commited (that's a mistake), however I don't think they should be explicitly moved to the .exe directory. They should always be relative the working directory, whether or not we put that into a separate folder is a more realistic question. It's nice to have them inside the project hierarchy in Visual Studio, so I'll leave them here for now.

**Comment by HerrDingenz** [comment]
Simply just add the profile files to .gitignore

**Comment by LovelySanta** [comment]
> Simply just add the profile files to .gitignore

We could rename them to `*.profiling.json` or something, and then we can indeed add them to the .gitignore, just adding *.json would be a bad idea, and hardcoding the names is only a temporary measure...

**Comment by HerrDingenz** [comment]
You are right @LovelySanta rename the files and then add them to .gitignore.

@freeman40 if you run the exe file from your bin folder they will be created right there next to the exe file. They only get created inside the sandbox project folder if you run it inside VS.

**Comment by TheCherno** [comment]
Closed (obsolete).

**Pull request closed without merging**
