### PR TITLE
fixed texture2d parameter

### PR DESCRIPTION
**Pull request by ThomasJowett**
#### Describe the issue (if no issue has been made)
A clear and concise description of what the issue is. Explain the difference between the expected and the current behavior.
A screenshot or copy of the error could be helpful as well.

#### PR impact _(Make sure to add [closing keywords](https://help.github.com/en/articles/closing-issues-using-keywords))_
List of related issues/PRs this will solve:

 Impact                  | Issue/PR
------------------------ | ------
Issues this solves       | None or #number(s)
Other PRs this solves    | None or #number(s)

#### Proposed fix _(Make sure you've read [on how to contribute](https://github.com/TheCherno/Hazel/blob/master/.github/CONTRIBUTING.md) to Hazel)_
A short description of what this fix is and how it fixed the issue you described.

#### Additional context
Add any other context about the solution here. Did you test the solution on all (relevant) platforms?
If not, create a [task list](https://help.github.com/en/articles/about-task-lists) here.

### CODE REVIEW

**Comment by MrBrN197** [comment]
You should add some context about what your trying to fix.

And in this case I don't think you've actually fixed anything.
`glTextureParameter` infact actually expects a texture not a target.

**Comment by ThomasJowett** [comment]
https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glTexParameter.xhtml

It expects a target as stated in the documentation.

**Comment by PhilipKatis** [comment]
`glTexParameteri` expects a target, but `glTextureParameteri` used in Hazel expects the texture ID.

**Comment by PhilipKatis** [comment]
`glTexParameteri` is the one that expects a target. But `glTextureParameteri` used in Hazel expects a texture.

**Pull request closed without merging**
